# Generated by Django 5.0.7 on 2025-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_item_size_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('D', 'Dress'), ('B', 'Blazer'), ('Sk', 'Skirt'), ('T', 'Tops')], default='S', max_length=2),
        ),
    ]
